import Image from "next/image";
import Link from "next/link";

export default function AboutPage() {
  return <main className="about-page about-full-page">
    <nav className="member-nav"><Link className="brand" href="/">Faith.In.Dance.</Link><div><Link href="/">Home</Link><Link href="/membership">Lessons + Tutorials</Link><Link href="/prayers">Prayers</Link><Link href="/book">Book</Link></div><Link className="nav-button" href="/book">Book now</Link></nav>
    <section className="about-page-hero"><div className="about-page-photo"><Image src="/images/faith-about.jpg" alt="Faith smiling outdoors" fill sizes="(max-width: 720px) 100vw, 45vw" priority /></div><div><p className="eyebrow">Meet Faith</p><h1>Building stronger dancers<br /><em>from the inside out.</em></h1><p>There are coaches who teach skills. And then there are coaches who have a way of helping young people discover what they&apos;re capable of. Faith is both.</p></div></section>
    <section className="about-story"><p className="eyebrow">Her story</p><div><div className="about-story-heading"><h2>Big goals.<br /><em>Real growth.</em></h2><div className="about-bb-photo"><Image src="/images/faith-bb.jpg" alt="Faith performing as a professional NBA dancer" fill sizes="(max-width: 720px) 100vw, 38vw" /></div></div><div className="about-story-copy"><p>Faith began dancing competitively at <strong>Laura Cote School of Dance</strong>. A former <strong>Division I dancer at Grand Canyon University, D1 UDA National Jazz Champion, and professional NBA dancer for the Minnesota Timberwolves</strong>, Faith knows firsthand what it means to set big goals, work relentlessly toward them, and perform at an elite level.</p><p>But what makes Faith such a special coach goes far beyond her own accomplishments. She understands that learning to dance is also learning to work hard, handle pressure, overcome disappointment, build confidence, and keep going when something doesn&apos;t come easily.</p><p>That ability isn&apos;t accidental.</p><p>Faith is completing her <strong>Bachelor of Science in Elementary Education with an emphasis in Special Education at Grand Canyon University</strong>, finishing her final semester through student teaching. She is also <strong>ASD Certified, CPR/First Aid Certified, EDAC Certified, and AT Trained.</strong></p><p>Her background in education and special education gives Faith an understanding that is incredibly valuable in private coaching: <strong>Every child is different. And every child deserves to be taught in a way that helps them succeed.</strong></p></div></div></section>
    <section className="about-photo-story"><div className="about-photo-story-image framed"><Image src="/images/faith-framed.jpg" alt="Faith holding a framed collection of dance memories" fill sizes="(max-width: 720px) 100vw, 45vw" /></div><div className="about-photo-story-copy"><p className="eyebrow">A coach in their corner</p><h2>Challenge with<br /><em>care.</em></h2><p>Faith meets dancers where they are while continuing to challenge them toward where they want to go. She knows when to break something down, when to approach it differently, when to encourage—and when a dancer is ready to be pushed a little harder.</p><p>Because confidence isn&apos;t built by convincing kids that everything will be easy.</p><strong>It&apos;s built by helping them discover that they can do hard things.</strong></div></section>
    <section className="mind-body-soul"><div className="mbs-intro"><p className="eyebrow">The heart behind Faith.In.Dance.</p><h2>Mind.<br />Body.<br /><em>Soul.</em></h2></div><article><span>Body</span><h3>Strength in motion.</h3><p>Developing strength, flexibility, technique, control, and the skills dancers need to reach their next level.</p></article><article><span>Mind</span><h3>Confidence under pressure.</h3><p>Building confidence, discipline, resilience, focus, and the courage to keep trying when something feels difficult.</p></article><article><span>Soul</span><h3>Grounded in who they are.</h3><p>Helping dancers stay grounded in who they are, encouraging kindness and character, and reminding them that their value reaches far beyond what happens on a competition stage.</p></article></section>
    <section className="about-champion"><div><p className="eyebrow">More than the stage</p><h2>Achievement matters.<br /><em>Identity matters more.</em></h2><p>And woven through all of it is Faith&apos;s relationship with <strong>Jesus</strong>. Her faith isn&apos;t simply something she talks about. It&apos;s reflected in the way she leads, encourages, teaches, and shows up for the young people who trust her to be in their corner.</p><p>Faith understands that dance can be an incredibly important part of a young person&apos;s life—but it should help build them, not define them.</p><p className="about-emphasis">A score doesn&apos;t define them. A placement doesn&apos;t define them. A mistake onstage doesn&apos;t define them. And neither does one difficult season of life.</p></div><div className="about-champion-image"><Image src="/images/faith-national-champions.jpg" alt="Faith holding a national championship trophy" fill sizes="(max-width: 720px) 100vw, 42vw" /></div></section>
    <section className="about-closing"><p>Faith.In.Dance. is about developing incredible dancers while helping build confident, resilient, and kind young people who know who they are, know what they&apos;re capable of, and aren&apos;t afraid to work for what they want.</p><h2>Because the greatest thing a coach can help a dancer build isn&apos;t just the next skill.<br /><em>It&apos;s the person they&apos;ll become along the way.</em></h2><Link className="button" href="/book">Work with Faith <span>→</span></Link></section>
    <footer><Link className="brand" href="/">Faith.In.Dance.</Link><span>Dance with confidence.</span><span>© 2026 Faith.In.Dance.</span></footer>
  </main>;
}
