import Link from "next/link";
import { BookingSlotPicker } from "@/components/booking-slot-picker";

const saturdayTimes = ["8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM"];
const sundayTimes = ["9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM"];

export default function BookPage() {
  return <main className="booking-page">
    <nav className="member-nav"><Link className="brand" href="/">Faith.In.Dance.</Link><div><Link href="/about">About</Link><Link href="/#lessons">Lessons</Link><Link href="/membership">Membership</Link><Link href="/prayers">Prayers</Link></div><Link className="nav-button" href="/book">Book now</Link></nav>
    <section className="booking-hero"><p className="eyebrow">August coaching weekend</p><h1>Make time<br /><em>to grow.</em></h1><p>For one weekend only, Faith is opening focused private sessions for dancers who want help with a skill, technique, routine, audition, or the confidence to take their next step.</p><div className="booking-dates"><div><span>Saturday</span><strong>August 29</strong><small>8 AM–9 PM</small></div><div><span>Sunday</span><strong>August 30</strong><small>8 AM–3 PM</small></div></div><div className="booking-fit"><span>Private Zoom or in-person coaching</span><span>30 or 60 minutes</span><span>One or two dancers</span></div></section>
    <section className="worship-class"><div><p className="eyebrow">Sunday special class</p><h2>Worship<br /><em>Dance Class.</em></h2><p>This class is all about using the gift of dance to worship and glorify God. We&apos;ll learn worship choreography, focus on dancing with meaning and emotion, and use movement as another way to praise God.</p><p>My hope is that you leave feeling encouraged, confident, and reminded of the beautiful gift God gave you to dance!</p></div><div className="worship-details"><p>Sunday, August 30</p><strong>8:00–9:00 AM</strong><span>In person · Laura Cote</span><b>Free</b><a className="button" href="#register">Register here <span>→</span></a></div></section>
    <section className="session-pricing"><p className="eyebrow">Private coaching options</p><h2>Choose the session<br /><em>that fits best.</em></h2><div className="price-grid"><article><p>In person</p><h3>One dancer</h3><small>Focused one-on-one attention</small><div><span>1 hour</span><b>$50</b></div><div><span>30 minutes</span><b>$25</b></div></article><article><p>In person</p><h3>Two dancers</h3><small>Train side by side · price per dancer</small><div><span>1 hour</span><b>$30 each</b></div><div><span>30 minutes</span><b>$20 each</b></div></article><article><p>Virtual</p><h3>Zoom coaching</h3><small>Live support from wherever you are</small><div><span>1 hour</span><b>$40</b></div><div><span>30 minutes</span><b>$25</b></div></article></div></section>
    <BookingSlotPicker />
    <footer><Link className="brand" href="/">Faith.In.Dance.</Link><span>Dance with confidence.</span><span>© 2026 Faith.In.Dance.</span></footer>
  </main>;
}
