import Link from "next/link";

const saturdayTimes = ["8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM"];
const sundayTimes = ["9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM"];

export default function BookPage() {
  return <main className="booking-page">
    <nav className="member-nav"><Link className="brand" href="/">Faith.In.Dance.</Link><div><Link href="/about">About</Link><Link href="/#lessons">Lessons</Link><Link href="/membership">Membership</Link></div><Link className="nav-button" href="/book">Book now</Link></nav>
    <section className="booking-hero"><p className="eyebrow">One special weekend with Faith</p><h1>Bring the goal.<br /><em>Let&apos;s work.</em></h1><p>These focused private sessions are for the dancer who wants experienced eyes on the skill, routine, audition, or confidence gap that is keeping her stuck. Faith will meet her where she is and give her a clear next step.</p><div className="booking-fit"><span>Private Zoom or in-person coaching</span><span>30 or 60 minutes</span><span>One or two dancers</span></div></section>
    <section className="worship-class"><div><p className="eyebrow">Sunday special class</p><h2>Worship<br /><em>Dance Class.</em></h2><p>This class is all about using the gift of dance to worship and glorify God. We&apos;ll learn worship choreography, focus on dancing with meaning and emotion, and use movement as another way to praise God.</p><p>My hope is that you leave feeling encouraged, confident, and reminded of the beautiful gift God gave you to dance!</p></div><div className="worship-details"><p>Sunday, August 30</p><strong>8:00–9:00 AM</strong><span>In person · Laura Cote</span><b>Free</b><a className="button" href="#register">Register here <span>→</span></a></div></section>
    <section className="session-pricing"><p className="eyebrow">Private coaching options</p><h2>Choose the support<br /><em>your dancer needs.</em></h2><div className="price-grid"><article><p>In person</p><h3>One dancer</h3><div><span>1 hour</span><b>$50</b></div><div><span>30 minutes</span><b>$25</b></div></article><article><p>In person</p><h3>Two dancers</h3><small>Price is per dancer</small><div><span>1 hour</span><b>$30 each</b></div><div><span>30 minutes</span><b>$20 each</b></div></article><article><p>Virtual</p><h3>Zoom coaching</h3><small>Price is per session</small><div><span>1 hour</span><b>$40</b></div><div><span>30 minutes</span><b>$25</b></div></article></div></section>
    <section className="availability"><p className="eyebrow">Weekend availability</p><h2>Pick a day and<br /><em>starting time.</em></h2><p className="availability-note">Thirty-minute and one-hour sessions are available. A time is not held until checkout is connected and completed.</p><div className="day-grid"><article><header><span>Saturday</span><h3>August 29</h3><p>8:00 AM–9:00 PM</p></header><div className="time-grid">{saturdayTimes.map((time) => <button type="button" key={time}>{time}</button>)}</div></article><article><header><span>Sunday</span><h3>August 30</h3><p>9:00 AM–3:00 PM</p></header><div className="time-grid">{sundayTimes.map((time) => <button type="button" key={time}>{time}</button>)}</div></article></div></section>
    <section className="booking-register" id="register"><div><p className="eyebrow">Reserve your spot</p><h2>Ready to<br /><em>dance?</em></h2><p>The booking form and secure Stripe checkout will be added next. Choose your lesson type and time here first, then we&apos;ll make the reservation flow live.</p></div><div className="booking-summary"><p>Your booking</p><span>Choose a session type</span><span>Choose a date and time</span><button type="button" className="button">Continue to booking <span>→</span></button><small>Secure payment will be added with Stripe.</small></div></section>
    <footer><Link className="brand" href="/">Faith.In.Dance.</Link><span>Dance with confidence.</span><span>© 2026 Faith.In.Dance.</span></footer>
  </main>;
}
