"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

const saturdayTimes = ["8:00 AM", "8:30 AM", "9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM", "3:00 PM", "3:30 PM", "4:00 PM", "4:30 PM", "5:00 PM", "5:30 PM", "6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM"];
const sundayTimes = ["9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "12:00 PM", "12:30 PM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM"];
const worshipPaymentUrl = "https://buy.stripe.com/3cI14nfs912R7TT7dQ3cc00";
const privatePaymentUrls: Record<string, Record<number, string>> = {
  "in-person-one": { 1: "https://buy.stripe.com/3cI3cvcfX26V8XX41E3cc01", 2: "https://buy.stripe.com/9B614n7ZHh1Pa21gOq3cc02" },
  "in-person-two": { 1: "https://buy.stripe.com/eVqfZhbbTbHv2zzdCe3cc03", 2: "https://buy.stripe.com/3cI28rdk1fXL4HH41E3cc04" },
};
type Day = "Saturday, August 29" | "Sunday, August 30";
type Slot = { key: string; label: string };

function slotKey(day: Day, time: string) {
  const date = day.startsWith("Saturday") ? "2026-08-29" : "2026-08-30";
  const [clock, meridiem] = time.split(" "); const [hourText, minute] = clock.split(":"); let hour = Number(hourText);
  if (meridiem === "PM" && hour !== 12) hour += 12; if (meridiem === "AM" && hour === 12) hour = 0;
  return `${date}T${String(hour).padStart(2, "0")}:${minute}`;
}

export function BookingSlotPicker() {
  const [selected, setSelected] = useState<Slot[]>([]); const [booked, setBooked] = useState<string[]>([]); const [sessionType, setSessionType] = useState("in-person-one"); const [status, setStatus] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch("/api/bookings").then((r) => r.ok ? r.json() : { bookedSlots: [] }).then((data) => setBooked(data.bookedSlots ?? [])).catch(() => undefined); }, []);
  useEffect(() => { const chooseWorship = () => { if (window.location.hash === "#register-worship") setSessionType("worship-class"); }; chooseWorship(); window.addEventListener("hashchange", chooseWorship); return () => window.removeEventListener("hashchange", chooseWorship); }, []);
  const isWorship = sessionType === "worship-class";
  const paymentUrl = isWorship ? worshipPaymentUrl : privatePaymentUrls[sessionType]?.[selected.length];
  const minutes = selected.length * 30; const duration = useMemo(() => minutes >= 60 ? `${Math.floor(minutes / 60)} hr${minutes >= 120 ? "s" : ""}${minutes % 60 ? ` ${minutes % 60} min` : ""}` : `${minutes} min`, [minutes]);
  function toggle(day: Day, time: string) { const slot = { key: slotKey(day, time), label: `${day} · ${time}` }; if (booked.includes(slot.key)) return; setSelected((current) => current.some((item) => item.key === slot.key) ? current.filter((item) => item.key !== slot.key) : current.length >= 2 ? current : [...current, slot]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected.length && !isWorship) return; const formElement = event.currentTarget; setSaving(true); setStatus(""); const form = new FormData(formElement); const response = await fetch("/api/bookings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), phone: form.get("phone"), dancerName: form.get("dancerName"), focus: form.get("focus"), sessionType, slots: isWorship ? [] : selected, notes: form.get("notes") }) }); const data = await response.json().catch(() => ({})); if (response.ok) { setBooked((current) => [...current, ...selected.map((slot) => slot.key)]); setSelected([]); formElement.reset(); if (paymentUrl && data.bookingId) { const checkout = new URL(paymentUrl); checkout.searchParams.set("client_reference_id", data.bookingId); setStatus("Your spot is saved. Taking you to secure payment…"); window.location.assign(checkout.toString()); return; } setStatus("Your time is saved! Faith will follow up with your booking details."); } else setStatus(data.error ?? "That time was just booked. Please choose another available time."); setSaving(false); }
  function dayCard(day: Day, times: string[]) { return <article><header><span>{day.startsWith("Saturday") ? "Saturday" : "Sunday"}</span><h3>{day.endsWith("29") ? "August 29" : "August 30"}</h3><p>{day.startsWith("Saturday") ? "8:00 AM–9:00 PM" : "9:00 AM–3:00 PM"}</p></header><div className="time-grid">{times.map((time) => { const key = slotKey(day, time); const active = selected.some((slot) => slot.key === key); const unavailable = booked.includes(key); return <button className={active ? "is-selected" : ""} type="button" disabled={unavailable} aria-pressed={active} key={time} onClick={() => toggle(day, time)}>{unavailable ? "Booked" : time}</button>; })}</div></article>; }
  return <><section className="availability"><p className="eyebrow">Weekend availability</p><h2>Choose every block<br /><em>you need.</em></h2><p className="availability-note">Every button is a 30-minute block. Choose two for one hour, or select more blocks for a longer session or multiple dancers. Booked times are unavailable.</p><div className="day-grid">{dayCard("Saturday, August 29", saturdayTimes)}{dayCard("Sunday, August 30", sundayTimes)}</div></section><section className="booking-register" id="register-worship"><div><p className="eyebrow">Your booking</p><h2>Build the session<br /><em>that works.</em></h2><p>Enter your details to save your in-person time with Faith. You&apos;ll continue securely to payment after your time is held.</p><label className="booking-session-label">Booking type<select value={sessionType} onChange={(event) => setSessionType(event.target.value)}><option value="in-person-one">In person · one dancer</option><option value="in-person-two">In person · two dancers</option><option value="worship-class">Sunday worship dance class · $10</option></select></label></div><form className="booking-summary" onSubmit={submit}><p>{isWorship ? "Your worship class" : "Your selected time"}</p>{isWorship ? <><strong>Sunday, August 30 · 8:00–9:00 AM</strong><span>In person at Laura Cote School of Dance · $10</span></> : selected.length ? <><strong>{selected.length} block{selected.length === 1 ? "" : "s"} · {duration}</strong><ul>{selected.map((slot) => <li key={slot.key}>{slot.label}</li>)}</ul></> : <span>Choose one or more time blocks above.</span>}<div className="booking-details"><label>Parent / dancer name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" type="email" required placeholder="you@example.com" /></label><label>Phone<input name="phone" type="tel" required placeholder="Phone number" /></label><label>Dancer name<input name="dancerName" placeholder="Optional" /></label><label>What would you like to work on?<select name="focus" required defaultValue=""><option value="" disabled>Select a coaching focus</option><option>Private Zoom lesson</option><option>In-person lesson</option><option>Tricks & technique</option><option>Performance prep</option><option>Audition or team placement</option><option>Confidence and encouragement</option><option>Something else</option></select></label><label>Anything Faith should know?<textarea name="notes" rows={3} placeholder="Optional" /></label></div><button type="submit" className="button" disabled={(!selected.length && !isWorship) || saving}>{saving ? "Saving…" : isWorship ? "Save my class spot" : "Save my booking"} <span>→</span></button>{status && <small className="booking-status">{status}</small>}<small>Your selected time is held while you complete secure payment.</small></form></section></>;
}
